server:
  port: 7878
spring:
  application:
    name: config-server
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    config:
      server:
        git:
          uri: https://github.com/kxiaozi123/springcloud_config.git
          default-label: dev
          basedir: D:\springcloud\configserver7878\src\main\resources\config
  rabbitmq:
    host: 192.168.154.130
    username: guest
    password: guest
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "*"
